(ns roman_numerals.test.core
  (:use [roman_numerals.core])
  (:use [clojure.test]))

(deftest test-to-roman
         (is (= "I" (to-roman 1)))
         (is (= "II" (to-roman 2)))
         (is (= "III" (to-roman 3)))
         (is (= "V" (to-roman 5)))
         (is (= "X" (to-roman 10)))
         (is (= "XX" (to-roman 20)))
         (is (= "L" (to-roman 50)))
         (is (= "C" (to-roman 100)))
         (is (= "D" (to-roman 500)))
         (is (= "M" (to-roman 1000)))
         (is (= "IV" (to-roman 4)))
         (is (= "IX" (to-roman 9)))
         (is (= "XL" (to-roman 40)))
         (is (= "XC" (to-roman 90)))
         (is (= "CD" (to-roman 400)))
         (is (= "CM" (to-roman 900)))
         (is (= "LXXXIX" (to-roman 89)))
         (is (= "MCMLXXXIV" (to-roman 1984)))
         (is (= "MMMCMXCIX" (to-roman 3999))))

